name: Build

on:
  push:
    branches: [ main ]
    paths: 
        - "source/**"
        - ".github/workflows/build.yml"

defaults:
  run:
    working-directory: "source/"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v3

    - name: Build and Publish head Docker image
      uses: VaultVulp/gp-docker-action@1.6.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: highscore-service
        build-context: ./source/Misy.Highscore.Service
        dockerfile: ./source/Misy.Highscore.Service/Dockerfile